name: Docker Image CI

on: 
  push:
    branches:
      - main # Using 'main' as the default branch name

jobs:
  build-and-push:
    runs-on: ubuntu-22.04-arm # Use ubuntu-latest for x86_64 host, or self-hosted for ARM if available

    steps:
    - name: Checkout code
      uses: actions/checkout@v4



    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image (linux/arm64)
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: joon78/kairox-ve:latest # Use the username from secrets
        cache-from: type=gha
        cache-to: type=gha,mode=max